version: "3.8"
services:
  cckl-app:
    container_name: cckl-admin
    build:
      context:  .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true